main:
#  empty:
#    type: Empty
#    input: /capra_camera/image
   decompress:
     type: UncompressImage
     input: /capra_camera/image
   compress:
     type: CompressImage
     input: decompress/output