banane:
  bgr2gray1:
    type: BGR2Gray
    order: 1
    input: /capra_camera/image
  facedetection1:
    type: CascadeClassifier
    order: 2
    input: bgr2gray1/output
  drawpolygons1:
    type: DrawPolygons
    order: 3
    color_red: 255
    thickness: 5
    input: /capra_camera/image
    polygons: facedetection1/faces