aaa:
  type: resize
  order: 3
  height: 600
  width: 800
  input: /capra_camera/image
resize1:
  type: resize
  order: 1
  height: 600
  width: 800
  input: aaa/output
resize2:
  type: resize
  order: 2
  height: 600
  input: resize1/output
  output: /potato